server:
  port: 9300
spring:
  application:
    name: springboot-couchbase
  couchbase:
    bootstrap-hosts: "127.0.0.1"
    bucket:
      name: jcgassignment
      password: password
  data:
    couchbase:
      auto-index: true